### PR TITLE
make it possible to use in chrome extension background script

### PR DESCRIPTION
**Pull request by IsaacHook**
- background scripts in chrome don't have access to window global
- extension.ts is mostly a copy of browser.ts with the reference to window removed & windowOnBeforeUnload removed

### CODE REVIEW

**Comment by TudorCRL** [comment]
@IsaacHook thanks for the contribution! We're going to put together a quick browser extension example so that we can test these code changes and once that's done we'll get them merged in

**Comment by IsaacHook** [comment]
nice thanks!
only got it working for chrome, but should be easy to extend for firefox etc as well

**Comment by TudorCRL** [comment]
@IsaacHook I've tested this PR now and it all seems to be working as you say - thanks for the contribution! There's just one thing needed before the merge, which is formatting it to fit the standards of the rest of the repo. I suspect you might have a formatter such as prettier configured in your IDE which seems to differ slightly from the one we use and has caused other changes in the diff. If you run `npm run format` from inside your local copy of the repo and commit those formatting changes, it should match the styling of the rest of the repo and remove the non-functional code changes in this PR so that we can merge

**Comment by IsaacHook** [comment]
Ok should have removed those file changes now.

Those changes came from the formatter for me.  tried with both npm & pnpm both seemed to ignore the biome config. disabled all extensions, tried reinstalling & using a separate terminal. must be something with my local setup if no one else is experiencing this. will look into it further when I have more time.

**Review by nickgerig — APPROVED** [review]

**Pull request merged**
